-- Add new DayType values for holiday tracking
ALTER TYPE "DayType" ADD VALUE IF NOT EXISTS 'HOLIDAY';
ALTER TYPE "DayType" ADD VALUE IF NOT EXISTS 'HOLIDAY_ADJACENT';
ALTER TYPE "DayType" ADD VALUE IF NOT EXISTS 'HOLIDAY_ADJACENT_SUNDAY';

-- Add comments
COMMENT ON TYPE "DayType" IS '날짜 유형: WEEKDAY(평일), SATURDAY(토요일), SUNDAY(일요일), HOLIDAY(공휴일), HOLIDAY_ADJACENT(공휴일 전후), HOLIDAY_ADJACENT_SUNDAY(공휴일 전후 일요일)';
