'use client'

import { useState, useRef, useEffect } from 'react'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Button } from '@/components/ui/button'
import { Checkbox } from '@/components/ui/checkbox'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { Plus, X, Calendar, Users, Upload, Download, AlertCircle, ChevronDown } from 'lucide-react'
import * as XLSX from 'xlsx'
import { Alert, AlertDescription } from '@/components/ui/alert'

interface Doctor {
  name: string
  shortName: string
  useCategory: boolean
  categories: Array<{
    name: string
    shortName: string
  }>
}

interface Combination {
  name: string
  dayOfWeek: string
  requiredStaff: number
  departmentRequiredStaff: { [departmentName: string]: number }
  // 부서별 구분별 필요 인원
  departmentCategoryStaff?: {
    [departmentName: string]: {
      [categoryName: string]: {
        count: number        // 필요 인원
        minRequired: number  // 꼭 필요 인원 (0이면 필수 아님)
      }
    }
  }
  doctors: string[]
  hasNightShift: boolean
}

interface CategoryRatios {
  [categoryName: string]: number // percentage (0-100)
}

interface Fairness {
  enableNightShiftFairness: boolean
  enableWeekendFairness: boolean
  enableHolidayFairness: boolean
  enableHolidayAdjacentFairness: boolean
}

interface Staff {
  name: string
  birthDate: string
  departmentName: string
  categoryName: string
  position: string
  workType: 'WEEK_4' | 'WEEK_5'
  flexibleForCategories: string[]
  flexibilityPriority: number
}

interface CombinationStepProps {
  data: Combination[]
  doctors: Doctor[]
  departments: { name: string; order: number; useAutoAssignment: boolean }[]
  staff: Staff[]  // 추가: 현재 직원 수 계산용
  fairness: Fairness
  categoryRatios: CategoryRatios
  categories: string[]
  onChange: (data: Combination[]) => void
  onFairnessChange: (fairness: Fairness) => void
  onCategoryRatiosChange: (ratios: CategoryRatios) => void
}

const DAYS_OF_WEEK = [
  { value: 'MONDAY', label: '월요일' },
  { value: 'TUESDAY', label: '화요일' },
  { value: 'WEDNESDAY', label: '수요일' },
  { value: 'THURSDAY', label: '목요일' },
  { value: 'FRIDAY', label: '금요일' },
  { value: 'SATURDAY', label: '토요일' },
  { value: 'SUNDAY', label: '일요일' },
]

export function CombinationStep({
  data,
  doctors,
  departments,
  staff,
  fairness,
  categoryRatios,
  categories,
  onChange,
  onFairnessChange,
  onCategoryRatiosChange,
}: CombinationStepProps) {
  const [newCombination, setNewCombination] = useState<Combination>({
    name: '',
    dayOfWeek: 'MONDAY',
    requiredStaff: 2,
    departmentRequiredStaff: {},
    doctors: [],
    hasNightShift: false,
  })
  const [selectedDoctorIndex, setSelectedDoctorIndex] = useState<number | null>(null)
  const [uploadError, setUploadError] = useState<string>('')
  const [expandedCombinations, setExpandedCombinations] = useState<Set<number>>(new Set())
  const fileInputRef = useRef<HTMLInputElement>(null)

  // 의사 목록 생성 (이름 표시용, shortName 조합명용)
  interface DoctorOption {
    displayName: string  // 화면 표시용: "박원장(상담)"
    shortName: string    // 조합명용: "박(상담)"
  }

  const getDoctorOptions = (): DoctorOption[] => {
    const options: DoctorOption[] = []
    doctors.forEach((doctor) => {
      if (doctor.useCategory && doctor.categories.length > 0) {
        doctor.categories.forEach((category) => {
          options.push({
            displayName: `${doctor.name}(${category.name})`,
            shortName: `${doctor.shortName}(${category.shortName || category.name})`
          })
        })
      } else {
        options.push({
          displayName: doctor.name,
          shortName: doctor.shortName
        })
      }
    })
    return options
  }

  const doctorOptions = getDoctorOptions()

  // 선택된 의사들로부터 조합명 자동 생성 (shortName 사용)
  const generateCombinationName = (selectedDoctors: string[]) => {
    return selectedDoctors.join('')
  }

  // 의사 추가 (버튼 클릭 방식)
  const toggleDoctor = (index: number) => {
    const doctorOption = doctorOptions[index]
    const doctorShortName = doctorOption.shortName

    // 이미 선택되어 있으면 제거, 없으면 추가
    const isSelected = newCombination.doctors.includes(doctorShortName)

    let updatedDoctors: string[]
    if (isSelected) {
      updatedDoctors = newCombination.doctors.filter(d => d !== doctorShortName)
    } else {
      updatedDoctors = [...newCombination.doctors, doctorShortName]
    }

    const autoGeneratedName = generateCombinationName(updatedDoctors)
    setNewCombination({
      ...newCombination,
      doctors: updatedDoctors,
      name: autoGeneratedName,
    })
  }

  // shortName으로 displayName 찾기
  const getDisplayName = (shortName: string): string => {
    const option = doctorOptions.find(opt => opt.shortName === shortName)
    return option?.displayName || shortName
  }

  const addCombination = () => {
    if (newCombination.name.trim() && newCombination.doctors.length > 0) {
      onChange([...data, { ...newCombination }])
      setNewCombination({
        name: '',
        dayOfWeek: 'MONDAY',
        requiredStaff: 0,
        departmentRequiredStaff: {},
        doctors: [],
        hasNightShift: false,
      })
    }
  }

  const removeCombination = (index: number) => {
    onChange(data.filter((_, i) => i !== index))
  }

  const toggleExpand = (index: number) => {
    const newExpanded = new Set(expandedCombinations)
    if (newExpanded.has(index)) {
      newExpanded.delete(index)
    } else {
      newExpanded.add(index)
    }
    setExpandedCombinations(newExpanded)
  }

  const updateCombinationCategoryCount = (
    combIndex: number,
    deptName: string,
    catName: string,
    value: number
  ) => {
    const updated = [...data]
    const combination = updated[combIndex]

    if (!combination.departmentCategoryStaff) {
      combination.departmentCategoryStaff = {}
    }
    if (!combination.departmentCategoryStaff[deptName]) {
      combination.departmentCategoryStaff[deptName] = {}
    }

    const deptRequired = combination.departmentRequiredStaff[deptName] || 0
    const current = combination.departmentCategoryStaff[deptName][catName] || { count: 0, minRequired: 0 }

    combination.departmentCategoryStaff[deptName][catName] = {
      count: Math.min(deptRequired, Math.max(0, value)),
      minRequired: Math.min(current.minRequired, value)
    }

    onChange(updated)
  }

  const updateCombinationMinRequired = (
    combIndex: number,
    deptName: string,
    catName: string,
    value: number
  ) => {
    const updated = [...data]
    const combination = updated[combIndex]

    if (!combination.departmentCategoryStaff) {
      combination.departmentCategoryStaff = {}
    }
    if (!combination.departmentCategoryStaff[deptName]) {
      combination.departmentCategoryStaff[deptName] = {}
    }

    const current = combination.departmentCategoryStaff[deptName][catName] || { count: 0, minRequired: 0 }

    combination.departmentCategoryStaff[deptName][catName] = {
      ...current,
      minRequired: value
    }

    onChange(updated)
  }

  // 부서별 인원 및 구분별 인원 자동 계산 헬퍼 함수
  const calculateDepartmentStaff = (requiredStaff: number) => {
    const autoAssignDepts = departments.filter(d => d.useAutoAssignment)

    if (autoAssignDepts.length === 0) {
      return {
        departmentRequiredStaff: {},
        departmentCategoryStaff: {}
      }
    }

    // 부서별 균등 배분
    const perDept = Math.floor(requiredStaff / autoAssignDepts.length)
    const remainder = requiredStaff % autoAssignDepts.length

    const departmentRequiredStaff: { [departmentName: string]: number } = {}
    autoAssignDepts.forEach((dept, index) => {
      departmentRequiredStaff[dept.name] = perDept + (index < remainder ? 1 : 0)
    })

    // 구분별 인원 자동 계산
    const departmentCategoryStaff: Combination['departmentCategoryStaff'] = {}

    autoAssignDepts.forEach(dept => {
      const deptRequired = departmentRequiredStaff[dept.name] || 0
      if (deptRequired === 0) return

      const deptStaff = staff.filter(s => s.departmentName === dept.name && s.categoryName)
      if (deptStaff.length === 0) {
        departmentCategoryStaff[dept.name] = {}
        return
      }

      const categoryCount: { [cat: string]: number } = {}
      deptStaff.forEach(s => {
        categoryCount[s.categoryName] = (categoryCount[s.categoryName] || 0) + 1
      })

      const totalStaff = deptStaff.length
      departmentCategoryStaff[dept.name] = {}

      Object.entries(categoryCount).forEach(([catName, count]) => {
        const ratio = count / totalStaff
        const allocatedCount = Math.round(deptRequired * ratio)

        if (allocatedCount > 0) {
          departmentCategoryStaff[dept.name]![catName] = {
            count: allocatedCount,
            minRequired: 0
          }
        }
      })
    })

    return { departmentRequiredStaff, departmentCategoryStaff }
  }

  // 부서별 필요 인원이 변경되면 자동으로 구분별 인원 계산
  useEffect(() => {
    const deptStaffKey = JSON.stringify(newCombination.departmentRequiredStaff)
    const hasDepartmentStaff = Object.values(newCombination.departmentRequiredStaff).some(count => count > 0)

    if (!hasDepartmentStaff) {
      // 부서별 인원이 없으면 구분별 인원도 초기화
      if (newCombination.departmentCategoryStaff && Object.keys(newCombination.departmentCategoryStaff).length > 0) {
        setNewCombination(prev => ({
          ...prev,
          departmentCategoryStaff: {}
        }))
      }
      return
    }

    const result: typeof newCombination.departmentCategoryStaff = {}

    departments
      .filter(dept => dept.useAutoAssignment)
      .forEach(dept => {
        const deptRequired = newCombination.departmentRequiredStaff[dept.name] || 0
        if (deptRequired === 0) return

        const deptStaff = staff.filter(s => s.departmentName === dept.name && s.categoryName)
        if (deptStaff.length === 0) {
          result[dept.name] = {}
          return
        }

        const categoryCount: { [cat: string]: number } = {}
        deptStaff.forEach(s => {
          categoryCount[s.categoryName] = (categoryCount[s.categoryName] || 0) + 1
        })

        const totalStaff = deptStaff.length
        result[dept.name] = {}

        Object.entries(categoryCount).forEach(([catName, count]) => {
          const ratio = count / totalStaff
          const allocatedCount = Math.round(deptRequired * ratio)

          // 기존 값이 있고 count가 동일하면 minRequired 유지
          const existingConfig = newCombination.departmentCategoryStaff?.[dept.name]?.[catName]
          result[dept.name]![catName] = {
            count: allocatedCount,
            minRequired: (existingConfig?.count === allocatedCount) ? (existingConfig.minRequired || 0) : 0
          }
        })
      })

    // 결과가 실제로 변경되었는지 확인 (무한 루프 방지)
    const currentStr = JSON.stringify(newCombination.departmentCategoryStaff || {})
    const newStr = JSON.stringify(result)

    if (currentStr !== newStr) {
      setNewCombination(prev => ({
        ...prev,
        departmentCategoryStaff: result
      }))
    }
  }, [JSON.stringify(newCombination.departmentRequiredStaff), staff.length, departments.length])

  // 엑셀 템플릿 다운로드
  const downloadTemplate = () => {
    // 저장된 조합이 있으면 실제 데이터 사용, 없으면 예제 사용
    const templateData = data.length > 0
      ? data.map((combination) => {
          const dayLabel = DAYS_OF_WEEK.find((d) => d.value === combination.dayOfWeek)?.label || combination.dayOfWeek
          const row: any = {
            조합명: combination.name,
            요일: dayLabel,
            필요인원: combination.requiredStaff,
            구분: combination.hasNightShift ? '야간' : '',
          }

          // 의사 정보 추가 (최대 10명)
          combination.doctors.forEach((doctor, index) => {
            row[`의사${index + 1}`] = doctor
          })

          return row
        })
      : [
          {
            조합명: '박(상담)구윤',
            요일: '월요일',
            필요인원: 2,
            구분: '',
            의사1: '박원장(상담)',
            의사2: '구원장',
            의사3: '윤원장',
          },
          {
            조합명: '구윤',
            요일: '월요일',
            필요인원: 2,
            구분: '야간',
            의사1: '구원장',
            의사2: '윤원장',
            의사3: '',
          },
        ]

    const ws = XLSX.utils.json_to_sheet(templateData)
    const wb = XLSX.utils.book_new()
    XLSX.utils.book_append_sheet(wb, ws, '의사조합')

    ws['!cols'] = [
      { wch: 15 },
      { wch: 10 },
      { wch: 10 },
      { wch: 10 },
      { wch: 15 },
      { wch: 15 },
      { wch: 15 },
    ]

    // 의사 목록 시트 추가 (참조용)
    const doctorListData = doctorOptions.length > 0
      ? doctorOptions.map(opt => ({ 의사명: opt.displayName, 조합명표시: opt.shortName }))
      : [{ 의사명: '원장 정보를 먼저 입력해주세요', 조합명표시: '-' }]
    const doctorListSheet = XLSX.utils.json_to_sheet(doctorListData)
    XLSX.utils.book_append_sheet(wb, doctorListSheet, '의사목록')

    XLSX.writeFile(wb, '의사조합_템플릿.xlsx')
  }


  // 엑셀 파일 업로드 처리
  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0]
    if (!file) return

    setUploadError('')

    const reader = new FileReader()
    reader.onload = (event) => {
      try {
        const workbook = XLSX.read(event.target?.result, { type: 'binary' })
        const sheetName = workbook.SheetNames[0]
        const worksheet = workbook.Sheets[sheetName]
        const jsonData = XLSX.utils.sheet_to_json(worksheet) as any[]

        if (jsonData.length === 0) {
          setUploadError('엑셀 파일에 데이터가 없습니다.')
          return
        }

        const newCombinations: Combination[] = []
        const errors: string[] = []

        jsonData.forEach((row, index) => {
          const rowNum = index + 2

          // 필수 필드 검증
          if (!row['조합명']) {
            errors.push(`${rowNum}행: 조합명이 누락되었습니다.`)
            return
          }

          if (!row['요일']) {
            errors.push(`${rowNum}행: 요일이 누락되었습니다.`)
            return
          }

          // 요일 변환
          const dayMapping: { [key: string]: string } = {
            월요일: 'MONDAY',
            화요일: 'TUESDAY',
            수요일: 'WEDNESDAY',
            목요일: 'THURSDAY',
            금요일: 'FRIDAY',
            토요일: 'SATURDAY',
            일요일: 'SUNDAY',
            월: 'MONDAY',
            화: 'TUESDAY',
            수: 'WEDNESDAY',
            목: 'THURSDAY',
            금: 'FRIDAY',
            토: 'SATURDAY',
            일: 'SUNDAY',
          }

          const dayStr = String(row['요일']).trim()
          const dayOfWeek = dayMapping[dayStr]
          if (!dayOfWeek) {
            errors.push(`${rowNum}행: 올바르지 않은 요일입니다. (${dayStr})`)
            return
          }

          // 필요인원 검증
          const requiredStaff = parseInt(String(row['필요인원'] || '2'))
          if (isNaN(requiredStaff) || requiredStaff < 1) {
            errors.push(`${rowNum}행: 필요인원은 1 이상의 숫자여야 합니다.`)
            return
          }

          // 의사 수집
          const combinationDoctors: string[] = []
          for (let i = 1; i <= 10; i++) {
            const doctorKey = `의사${i}`
            if (row[doctorKey] && String(row[doctorKey]).trim()) {
              const doctorName = String(row[doctorKey]).trim()

              // 의사 존재 여부 확인 (displayName 또는 shortName 허용)
              const doctorOption = doctorOptions.find(
                opt => opt.displayName === doctorName || opt.shortName === doctorName
              )

              if (!doctorOption) {
                errors.push(
                  `${rowNum}행: 존재하지 않는 의사입니다. (${doctorName})`
                )
                return
              }

              // shortName을 저장 (조합명용)
              combinationDoctors.push(doctorOption.shortName)
            }
          }

          if (combinationDoctors.length === 0) {
            errors.push(`${rowNum}행: 최소 1명의 의사가 필요합니다.`)
            return
          }

          // 야간 진료 여부 (구분 컬럼에서 확인)
          const hasNightShift = String(row['구분'] || '').trim() === '야간'

          // 부서별 인원 및 구분별 인원 자동 계산
          const { departmentRequiredStaff, departmentCategoryStaff } = calculateDepartmentStaff(requiredStaff)

          newCombinations.push({
            name: String(row['조합명']).trim(),
            dayOfWeek,
            requiredStaff,
            departmentRequiredStaff,
            departmentCategoryStaff,
            doctors: combinationDoctors,
            hasNightShift,
          })
        })

        if (errors.length > 0) {
          setUploadError(errors.join('\n'))
          return
        }

        // 기존 데이터에 추가
        onChange([...data, ...newCombinations])

        alert(`${newCombinations.length}개의 조합이 추가되었습니다.`)

        if (fileInputRef.current) {
          fileInputRef.current.value = ''
        }
      } catch (error) {
        console.error('Excel upload error:', error)
        setUploadError('엑셀 파일을 읽는 중 오류가 발생했습니다.')
      }
    }

    reader.readAsBinaryString(file)
  }

  return (
    <div className="space-y-6">
      <div className="text-center mb-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-2">의사 조합 설정</h2>
        <p className="text-gray-600">
          일 패턴에 사용될 의사 조합을 요일별로 설정해주세요
        </p>
      </div>

      {/* 엑셀 업로드 섹션 */}
      <div className="p-4 bg-gradient-to-r from-green-50 to-blue-50 rounded-lg border border-green-200">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Upload className="w-5 h-5 text-green-600" />
            <div>
              <h3 className="font-semibold text-gray-900">엑셀로 일괄 등록</h3>
              <p className="text-sm text-gray-600">
                여러 개의 조합을 한 번에 등록할 수 있습니다
              </p>
            </div>
          </div>
          <div className="flex gap-2">
            <Button
              variant="outline"
              size="sm"
              onClick={downloadTemplate}
              className="h-9 border-green-300 hover:bg-green-50"
            >
              <Download className="w-4 h-4 mr-1" />
              템플릿 다운로드
            </Button>
            <input
              ref={fileInputRef}
              type="file"
              accept=".xlsx,.xls"
              onChange={handleFileUpload}
              className="hidden"
            />
            <Button
              size="sm"
              onClick={() => fileInputRef.current?.click()}
              className="h-9 bg-green-600 hover:bg-green-700"
            >
              <Upload className="w-4 h-4 mr-1" />
              엑셀 업로드
            </Button>
          </div>
        </div>
      </div>

      {/* 업로드 에러 메시지 */}
      {uploadError && (
        <Alert variant="destructive">
          <AlertCircle className="h-4 w-4" />
          <AlertDescription className="whitespace-pre-line">
            {uploadError}
          </AlertDescription>
        </Alert>
      )}

      {/* 조합 목록 */}
      {data.length > 0 && (
        <div className="space-y-3">
          {data.map((combination, index) => {
            const isExpanded = expandedCombinations.has(index)
            // 자동배치 부서가 있으면 펼침 버튼 표시
            const hasAutoAssignDepts = departments.some(d => d.useAutoAssignment)
            const hasDeptStaff = hasAutoAssignDepts && (
              Object.keys(combination.departmentRequiredStaff || {}).some(
                dept => (combination.departmentRequiredStaff[dept] || 0) > 0
              ) || combination.requiredStaff > 0
            )

            return (
              <div
                key={index}
                className="bg-white rounded-lg border border-gray-200 overflow-hidden"
              >
                <div className="p-4 bg-gray-50">
                  <div className="flex items-start justify-between">
                    <div className="flex items-center gap-3 flex-1">
                      <Calendar className="w-5 h-5 text-blue-600" />
                      <div className="flex-1">
                        <h3 className="font-semibold text-lg">{combination.name}</h3>
                        <div className="flex items-center gap-3 mt-1 text-sm text-gray-600">
                          <span className="inline-flex items-center gap-1">
                            📅{' '}
                            {DAYS_OF_WEEK.find((d) => d.value === combination.dayOfWeek)
                              ?.label || combination.dayOfWeek}
                          </span>
                          <span className="inline-flex items-center gap-1">
                            👥 필요인원: {
                              Object.keys(combination.departmentRequiredStaff || {}).length > 0
                                ? Object.entries(combination.departmentRequiredStaff)
                                    .filter(([_, count]) => count > 0)
                                    .map(([dept, count]) => `${dept} ${count}명`)
                                    .join(', ')
                                : `${combination.requiredStaff}명 (전체)`
                            }
                          </span>
                          {combination.hasNightShift && (
                            <span className="inline-flex items-center gap-1 px-2 py-0.5 bg-indigo-100 text-indigo-700 rounded text-xs font-medium">
                              🌙 야간진료
                            </span>
                          )}
                        </div>
                      </div>
                    </div>
                    <div className="flex items-center gap-2">
                      {hasDeptStaff && (
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => toggleExpand(index)}
                          className="h-8 w-8 p-0"
                        >
                          <ChevronDown className={`w-4 h-4 transition-transform ${isExpanded ? 'rotate-180' : ''}`} />
                        </Button>
                      )}
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={() => removeCombination(index)}
                        className="h-8 w-8 p-0 hover:bg-red-100 hover:text-red-600"
                      >
                        <X className="w-4 h-4" />
                      </Button>
                    </div>
                  </div>

                  <div className="ml-8 mt-3">
                    <Label className="text-xs text-gray-500 mb-2 block">
                      의사 구성:
                    </Label>
                    <div className="flex flex-wrap gap-2">
                      {combination.doctors.map((doctorShortName, docIndex) => (
                        <span
                          key={docIndex}
                          className="inline-flex items-center px-3 py-1 bg-blue-100 text-blue-700 rounded-full text-sm font-medium"
                        >
                          {getDisplayName(doctorShortName)}
                        </span>
                      ))}
                    </div>
                  </div>
                </div>

                {/* 펼쳐진 경우 구분별 상세 인원 표시 */}
                {isExpanded && hasDeptStaff && (
                  <div className="p-4 border-t border-gray-200 bg-white space-y-4">
                    <div className="flex items-center justify-between mb-2">
                      <Label className="text-sm font-semibold text-blue-700">구분별 상세 인원</Label>
                      {(!combination.departmentRequiredStaff || Object.keys(combination.departmentRequiredStaff).length === 0) && (
                        <Button
                          variant="outline"
                          size="sm"
                          onClick={() => {
                            const { departmentRequiredStaff, departmentCategoryStaff } = calculateDepartmentStaff(combination.requiredStaff)
                            const updated = [...data]
                            updated[index] = {
                              ...combination,
                              departmentRequiredStaff,
                              departmentCategoryStaff
                            }
                            onChange(updated)
                          }}
                          className="h-7 text-xs"
                        >
                          자동 계산
                        </Button>
                      )}
                    </div>

                    {(!combination.departmentRequiredStaff || Object.keys(combination.departmentRequiredStaff).length === 0) ? (
                      <div className="p-4 bg-blue-50 border border-blue-200 rounded text-center">
                        <p className="text-sm text-blue-900">
                          위의 "자동 계산" 버튼을 눌러 부서별/구분별 인원을 설정해주세요.
                        </p>
                      </div>
                    ) : (
                      departments
                        .filter(dept => dept.useAutoAssignment && (combination.departmentRequiredStaff[dept.name] || 0) > 0)
                        .map(dept => {
                        const deptRequired = combination.departmentRequiredStaff[dept.name] || 0
                        const deptStaff = staff.filter(s => s.departmentName === dept.name && s.categoryName)
                        const deptCategories = Array.from(new Set(deptStaff.map(s => s.categoryName)))

                        if (deptCategories.length === 0) {
                          return (
                            <div key={dept.name} className="p-3 bg-amber-50 border border-amber-200 rounded">
                              <p className="text-xs text-amber-900">
                                ⚠️ {dept.name} 부서에 구분이 설정된 직원이 없습니다.
                              </p>
                            </div>
                          )
                        }

                        const currentStaff = combination.departmentCategoryStaff?.[dept.name] || {}

                        return (
                          <div key={dept.name} className="p-4 bg-gray-50 border border-gray-200 rounded-lg">
                            <h4 className="font-semibold text-sm mb-3">{dept.name} (총 {deptRequired}명)</h4>
                            <div className="space-y-2">
                              {deptCategories.map(cat => {
                                const config = currentStaff[cat] || { count: 0, minRequired: 0 }

                                return (
                                  <div key={cat} className="grid grid-cols-[120px_1fr_1fr] gap-4 items-center p-2 bg-white rounded">
                                    <Label className="text-xs font-medium">{cat}</Label>

                                    <div className="flex items-center gap-2">
                                      <Label className="text-xs text-gray-500 w-12">인원:</Label>
                                      <Input
                                        type="number"
                                        min={0}
                                        max={deptRequired}
                                        value={config.count}
                                        onChange={(e) =>
                                          updateCombinationCategoryCount(
                                            index,
                                            dept.name,
                                            cat,
                                            parseInt(e.target.value) || 0
                                          )
                                        }
                                        className="h-8 flex-1"
                                      />
                                      <span className="text-xs text-gray-600">명</span>
                                    </div>

                                    <div className="flex items-center gap-2">
                                      <Checkbox
                                        id={`min-${index}-${dept.name}-${cat}`}
                                        checked={config.minRequired > 0}
                                        onCheckedChange={(checked) =>
                                          updateCombinationMinRequired(
                                            index,
                                            dept.name,
                                            cat,
                                            checked ? config.count : 0
                                          )
                                        }
                                      />
                                      <Label
                                        htmlFor={`min-${index}-${dept.name}-${cat}`}
                                        className="text-xs cursor-pointer flex-1"
                                      >
                                        필수
                                      </Label>
                                      {config.minRequired > 0 && (
                                        <>
                                          <Input
                                            type="number"
                                            min={0}
                                            max={config.count}
                                            value={config.minRequired}
                                            onChange={(e) =>
                                              updateCombinationMinRequired(
                                                index,
                                                dept.name,
                                                cat,
                                                Math.min(config.count, Math.max(0, parseInt(e.target.value) || 0))
                                              )
                                            }
                                            className="h-8 w-20"
                                          />
                                          <div className="flex items-center gap-1 px-2 py-1 bg-green-50 border border-green-200 rounded">
                                            <span className="text-xs text-green-700 font-medium">
                                              유연: {config.count - config.minRequired}명
                                            </span>
                                          </div>
                                        </>
                                      )}
                                    </div>
                                  </div>
                                )
                              })}
                            </div>
                          </div>
                        )
                      })
                    )}
                  </div>
                )}
              </div>
            )
          })}
        </div>
      )}

      {/* 새 조합 추가 */}
      <div className="p-5 bg-gray-50 rounded-lg border border-gray-200">
        <div className="flex items-center gap-2 mb-4">
          <Users className="w-5 h-5 text-blue-600" />
          <h3 className="font-semibold">새 조합 추가</h3>
        </div>

        <div className="space-y-4">
          {/* 조합명, 요일 */}
          <div className="grid md:grid-cols-2 gap-3">
            <div className="space-y-1">
              <Label className="text-xs">조합명 * (자동 생성, 수정 가능)</Label>
              <Input
                value={newCombination.name}
                onChange={(e) =>
                  setNewCombination({ ...newCombination, name: e.target.value })
                }
                placeholder="의사를 선택하면 자동 생성됩니다"
                className="h-9"
              />
            </div>

            <div className="space-y-1">
              <Label className="text-xs">요일 *</Label>
              <Select
                value={newCombination.dayOfWeek}
                onValueChange={(value) =>
                  setNewCombination({ ...newCombination, dayOfWeek: value })
                }
              >
                <SelectTrigger className="h-9">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {DAYS_OF_WEEK.map((day) => (
                    <SelectItem key={day.value} value={day.value}>
                      {day.label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </div>

          {/* 부서별 필요 인원 */}
          <div className="space-y-2">
            <Label className="text-xs font-semibold">부서별 필요 인원 *</Label>
            <div className="space-y-2 p-3 bg-blue-50 rounded border border-blue-200">
              {departments
                .filter(dept => dept.useAutoAssignment)
                .map((dept) => (
                  <div key={dept.name} className="flex items-center gap-2">
                    <Label className="text-xs w-20">{dept.name}</Label>
                    <Input
                      type="number"
                      min={0}
                      value={newCombination.departmentRequiredStaff[dept.name] || 0}
                      onChange={(e) =>
                        setNewCombination({
                          ...newCombination,
                          departmentRequiredStaff: {
                            ...newCombination.departmentRequiredStaff,
                            [dept.name]: parseInt(e.target.value) || 0,
                          },
                          // 전체 합계도 업데이트 (레거시 호환용)
                          requiredStaff: Object.values({
                            ...newCombination.departmentRequiredStaff,
                            [dept.name]: parseInt(e.target.value) || 0,
                          }).reduce((sum, val) => sum + val, 0),
                        })
                      }
                      className="h-8 flex-1"
                    />
                    <span className="text-xs text-gray-600">명</span>
                  </div>
                ))}
            </div>
            {departments.filter(d => d.useAutoAssignment).length === 0 && (
              <p className="text-xs text-amber-700 bg-amber-50 p-2 rounded border border-amber-200">
                ⚠️ 자동배치를 사용하는 부서가 없습니다. 2단계에서 설정해주세요.
              </p>
            )}
          </div>

          {/* 구분별 상세 인원 설정 */}
          {Object.entries(newCombination.departmentRequiredStaff).some(([dept, count]) =>
            departments.find(d => d.name === dept && d.useAutoAssignment) && count > 0
          ) && (
            <div className="space-y-3">
              <Label className="text-sm font-semibold text-blue-700">구분별 상세 인원 (자동 계산됨)</Label>

              {departments
                .filter(dept => dept.useAutoAssignment && (newCombination.departmentRequiredStaff[dept.name] || 0) > 0)
                .map(dept => {
                  const deptRequired = newCombination.departmentRequiredStaff[dept.name] || 0
                  const deptStaff = staff.filter(s => s.departmentName === dept.name && s.categoryName)
                  const deptCategories = Array.from(new Set(deptStaff.map(s => s.categoryName)))

                  if (deptCategories.length === 0) {
                    return (
                      <div key={dept.name} className="p-3 bg-amber-50 border border-amber-200 rounded">
                        <p className="text-xs text-amber-900">
                          ⚠️ {dept.name} 부서에 구분이 설정된 직원이 없습니다.
                        </p>
                      </div>
                    )
                  }

                  const currentStaff = newCombination.departmentCategoryStaff?.[dept.name] || {}

                  return (
                    <div key={dept.name} className="p-4 bg-white border border-gray-200 rounded-lg">
                      <h4 className="font-semibold text-sm mb-3">{dept.name} (총 {deptRequired}명)</h4>
                      <div className="space-y-2">
                        {deptCategories.map(cat => {
                          const config = currentStaff[cat] || { count: 0, minRequired: 0 }

                          return (
                            <div key={cat} className="p-2 bg-gray-50 rounded">
                              <div className="flex items-center gap-2 flex-wrap">
                                {/* 구분명 */}
                                <div className="w-24 flex-shrink-0">
                                  <Label className="text-xs font-medium">{cat}</Label>
                                </div>

                                {/* 인원 */}
                                <div className="flex items-center gap-1">
                                  <Label className="text-xs text-gray-500">인원:</Label>
                                  <Input
                                    type="number"
                                    min={0}
                                    max={deptRequired}
                                    value={config.count}
                                    onChange={(e) => {
                                      const value = Math.min(deptRequired, Math.max(0, parseInt(e.target.value) || 0))
                                      setNewCombination({
                                        ...newCombination,
                                        departmentCategoryStaff: {
                                          ...newCombination.departmentCategoryStaff,
                                          [dept.name]: {
                                            ...currentStaff,
                                            [cat]: {
                                              count: value,
                                              minRequired: Math.min(config.minRequired, value)
                                            }
                                          }
                                        }
                                      })
                                    }}
                                    className="h-8 w-16"
                                  />
                                  <span className="text-xs text-gray-600">명</span>
                                </div>

                                {/* 필수 체크박스 */}
                                <div className="flex items-center gap-1">
                                  <Checkbox
                                    id={`min-${dept.name}-${cat}`}
                                    checked={config.minRequired > 0}
                                    onCheckedChange={(checked) => {
                                      setNewCombination({
                                        ...newCombination,
                                        departmentCategoryStaff: {
                                          ...newCombination.departmentCategoryStaff,
                                          [dept.name]: {
                                            ...currentStaff,
                                            [cat]: {
                                              ...config,
                                              minRequired: checked ? config.count : 0
                                            }
                                          }
                                        }
                                      })
                                    }}
                                  />
                                  <Label htmlFor={`min-${dept.name}-${cat}`} className="text-xs cursor-pointer">
                                    필수
                                  </Label>
                                </div>

                                {/* 필수 인원 입력 */}
                                {config.minRequired > 0 && (
                                  <>
                                    <Input
                                      type="number"
                                      min={0}
                                      max={config.count}
                                      value={config.minRequired}
                                      onChange={(e) => {
                                        const value = Math.min(config.count, Math.max(0, parseInt(e.target.value) || 0))
                                        setNewCombination({
                                          ...newCombination,
                                          departmentCategoryStaff: {
                                            ...newCombination.departmentCategoryStaff,
                                            [dept.name]: {
                                              ...currentStaff,
                                              [cat]: {
                                                ...config,
                                                minRequired: value
                                              }
                                            }
                                          }
                                        })
                                      }}
                                      className="h-8 w-16"
                                    />
                                    <span className="text-xs text-gray-600">명</span>

                                    {/* 유연 인원 표시 */}
                                    <div className="flex items-center gap-1 px-2 py-1 bg-green-50 border border-green-200 rounded">
                                      <span className="text-xs text-green-700 font-medium">
                                        유연: {config.count - config.minRequired}명
                                      </span>
                                    </div>
                                  </>
                                )}
                              </div>
                            </div>
                          )
                        })}
                      </div>
                    </div>
                  )
                })}

              <p className="text-xs text-gray-600 bg-blue-50 p-2 rounded">
                💡 <strong>필수 인원:</strong> 체크하면 자동배치 시 반드시 배치되어야 하는 최소 인원입니다.
              </p>
            </div>
          )}

          {/* 야간 진료 여부 */}
          <div className="flex items-center space-x-2">
            <Checkbox
              id="hasNightShift"
              checked={newCombination.hasNightShift}
              onCheckedChange={(checked) =>
                setNewCombination({
                  ...newCombination,
                  hasNightShift: checked === true,
                })
              }
            />
            <Label
              htmlFor="hasNightShift"
              className="text-sm font-medium cursor-pointer"
            >
              🌙 야간 진료 포함
            </Label>
          </div>

          {/* 의사 선택 - 버튼 방식 */}
          <div className="space-y-2">
            <Label className="text-xs">의사 선택 * (클릭하여 선택/해제)</Label>
            <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-2 p-3 bg-gray-50 rounded border border-gray-200">
              {doctorOptions.map((option, index) => {
                const isSelected = newCombination.doctors.includes(option.shortName)
                return (
                  <Button
                    key={index}
                    type="button"
                    variant={isSelected ? "default" : "outline"}
                    size="sm"
                    onClick={() => toggleDoctor(index)}
                    className={`h-auto py-2 px-3 justify-start text-left ${
                      isSelected
                        ? 'bg-blue-600 hover:bg-blue-700 text-white'
                        : 'hover:bg-gray-100'
                    }`}
                  >
                    <span className="truncate">{option.displayName}</span>
                  </Button>
                )
              })}
            </div>

            {/* 선택된 의사 목록 표시 */}
            {newCombination.doctors.length > 0 && (
              <div className="text-xs text-gray-600 p-2 bg-blue-50 rounded border border-blue-200">
                선택됨: {newCombination.doctors.map(d => getDisplayName(d)).join(', ')}
              </div>
            )}
          </div>

          <Button
            onClick={addCombination}
            disabled={
              !newCombination.name.trim() || newCombination.doctors.length === 0
            }
            className="w-full h-10 bg-blue-600"
          >
            <Plus className="w-4 h-4 mr-2" />
            조합 추가
          </Button>
        </div>
      </div>

      {/* 형평성 설정 */}
      <div className="p-5 bg-gray-50 rounded-lg border border-gray-200">
        <h3 className="font-semibold mb-4 text-gray-900">형평성 기반 근무 배치</h3>
        <p className="text-sm text-gray-600 mb-4">
          사용할 형평성 항목을 선택하세요. 각 항목은 독립적으로 관리됩니다.
        </p>
        <div className="space-y-3">
          <div className="flex items-start space-x-3 p-3 bg-white rounded-lg border border-gray-200">
            <Checkbox
              id="fairness-night"
              checked={fairness.enableNightShiftFairness}
              onCheckedChange={(checked) =>
                onFairnessChange({ ...fairness, enableNightShiftFairness: checked as boolean })
              }
            />
            <div className="flex-1">
              <Label htmlFor="fairness-night" className="cursor-pointer font-medium text-gray-900">
                야간 근무 형평성
              </Label>
              <p className="text-xs text-gray-500 mt-1">
                평일 야간 진료 근무 횟수를 추적합니다
              </p>
            </div>
          </div>

          <div className="flex items-start space-x-3 p-3 bg-white rounded-lg border border-gray-200">
            <Checkbox
              id="fairness-weekend"
              checked={fairness.enableWeekendFairness}
              onCheckedChange={(checked) =>
                onFairnessChange({ ...fairness, enableWeekendFairness: checked as boolean })
              }
            />
            <div className="flex-1">
              <Label htmlFor="fairness-weekend" className="cursor-pointer font-medium text-gray-900">
                주말 근무 형평성
              </Label>
              <p className="text-xs text-gray-500 mt-1">
                토요일 근무 횟수를 추적합니다
              </p>
            </div>
          </div>

          <div className="flex items-start space-x-3 p-3 bg-white rounded-lg border border-gray-200">
            <Checkbox
              id="fairness-holiday"
              checked={fairness.enableHolidayFairness}
              onCheckedChange={(checked) =>
                onFairnessChange({ ...fairness, enableHolidayFairness: checked as boolean })
              }
            />
            <div className="flex-1">
              <Label htmlFor="fairness-holiday" className="cursor-pointer font-medium text-gray-900">
                공휴일 근무 형평성
              </Label>
              <p className="text-xs text-gray-500 mt-1">
                공휴일 근무 횟수를 추적합니다 (일요일 제외, 단 공휴일과 붙어있는 일요일은 포함)
              </p>
            </div>
          </div>

          <div className="flex items-start space-x-3 p-3 bg-white rounded-lg border border-gray-200">
            <Checkbox
              id="fairness-holiday-adjacent"
              checked={fairness.enableHolidayAdjacentFairness}
              onCheckedChange={(checked) =>
                onFairnessChange({ ...fairness, enableHolidayAdjacentFairness: checked as boolean })
              }
            />
            <div className="flex-1">
              <Label htmlFor="fairness-holiday-adjacent" className="cursor-pointer font-medium text-gray-900">
                공휴일 전후 근무 형평성
              </Label>
              <p className="text-xs text-gray-500 mt-1">
                공휴일 전날/다음날 근무 횟수를 추적합니다 (예: 5월 3일(토), 5월 6일(화) 등)
              </p>
            </div>
          </div>
        </div>
      </div>

      <div className="p-4 bg-blue-50 rounded-lg border border-blue-100">
        <p className="text-sm text-blue-900">
          💡 <strong>안내:</strong> 의사 조합은 하루의 진료 패턴을 의미합니다.
          예를 들어 "월요일 조합"으로 박(상담)구윤 / 구윤 / 박(진료)구윤 3가지
          조합을 만들 수 있습니다.
        </p>
      </div>
    </div>
  )
}
